apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# 1. Point to the universal truth (Your local manifests)
resources:
- ../../base

# 2. The Mutation: Intercept and replace the images

images:
- name: mdq-api:latest
  newName: 329177708612.dkr.ecr.us-west-2.amazonaws.com/mdq-api
  newTag: 2258ab1e0193c808984b8afcbbeecb7bae901706
- name: mdq-worker:latest
  newName: 329177708612.dkr.ecr.us-west-2.amazonaws.com/mdq-worker
  newTag: 2258ab1e0193c808984b8afcbbeecb7bae901706
