apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration
spec:
  backoffLimit: 3 # If it fails 3 times, stop trying
  template:
    spec:
      containers:
      - name: migrate
        image: mdq-api:latest
        imagePullPolicy: IfNotPresent
        args: ["./app", "-migrate"]
        env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: DATABASE_URL
      restartPolicy: OnFailure # CRITICAL: This is what makes it a Job, not a Deployment