name: Build and Push Backend

on:
  push:
    branches: [ "main" ]
    paths:
      - 'backend/**'
      - '.github/workflows/eks-backend.yml'
  workflow_dispatch: 

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-west-2
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-push:
    name: Build & Push to ECR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push API Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        working-directory: ./backend
        run: |
          docker build --build-arg APP_NAME=api -t $ECR_REGISTRY/mdq-api:$IMAGE_TAG .
          docker push $ECR_REGISTRY/mdq-api:$IMAGE_TAG

      - name: Build and Push Worker Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        working-directory: ./backend
        run: |
          docker build --build-arg APP_NAME=worker -t $ECR_REGISTRY/mdq-worker:$IMAGE_TAG .
          docker push $ECR_REGISTRY/mdq-worker:$IMAGE_TAG